openapi: 3.0.0
info:
  title: Image Suggestion API
  description: Documentation for Image Suggestion REST API endpoints
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: Wikimedia Platform Engineering Team
    url: https://www.mediawiki.org/wiki/Platform_Engineering_Team
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
  x-default-params:
    domain: api.wikimedia.org

paths:
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      description: Gets information about the service
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  version:
                    type: string
                  description:
                    type: string
      x-amples:
        - title: retrieve service info
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
              description: /.+/
              version: /.+/
  # from routes/imageSuggestions.js
  /image-suggestions/v0/{wiki}/{lang}/pages:
    get:
      tags:
        - Image Suggestions
      description: Gets image suggestions for under-illustrated pages
      parameters:
        - $ref: "#/components/parameters/wiki"
        - $ref: "#/components/parameters/lang"
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/seed"
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/offset"
        - $ref: "#/components/parameters/source"
        - $ref: "#/components/parameters/nofilter"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  seed: 
                    type: integer
                  pages: 
                    type: array
                    items:
                      type: object
                      properties:
                        page:
                          type: string  
                        project:
                          type: string
                        suggestions:
                          type: array
                          items:
                            $ref: "#/components/schemas/suggestion"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
      x-amples:
        - title: Gets image suggestions from the Image Matching Algorithm for under-illustrated pages
          request:
            query:
              seed: '0'
              limit: '5'
              offset: '0'
              source: 'ima'
            params:
              wiki: wikipedia
              lang: ar
          response:
            status: 200
            headers:
              content-type: application/json
  # from routes/imageSuggestions.js
  /image-suggestions/v0/{wiki}/{lang}/pages/{title}:
    get:
      tags:
        - Image Suggestions
      description: Gets image suggestions for an under-illustrated page
      parameters:
        - $ref: "#/components/parameters/wiki"
        - $ref: "#/components/parameters/lang"
        - $ref: "#/components/parameters/title"
        - $ref: "#/components/parameters/source"
        - $ref: "#/components/parameters/nofilter"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  seed:
                    type: integer
                  pages:
                    type: array
                    items:
                      type: object
                      properties:
                        page:
                          type: string
                        project:
                          type: string
                        suggestions:
                          type: array
                          items:
                            $ref: "#/components/schemas/suggestion"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
      x-amples:
        - title: Gets image suggestions from the Image Matching Algorithm for under-illustrated pages
          request:
            query:
              seed: '0'
              limit: '5'
              offset: '0'
              source: 'ima'
            params:
              wiki: wikipedia
              lang: ar
          response:
            status: 200
            headers:
              content-type: application/json
components:
  schemas:
    problem:
      required:
        - type
      properties:
        detail:
          type: string
    suggestion:
      required:
        - type
      properties:
        filename:
          type: string
        confidence_rating:
          type: string
        source:
          type: object
          properties:
            name: 
              type: string
            details: 
              $ref: "#/components/schemas/details"
    details:
      required:
        - type
      properties:
        from:
          type: string
        found_on:
          type: string
        dataset_id:
          type: string
      description: |
        further details about a "suggestion" block. Fields may vary by suggestion type.
  parameters:
    id:
      in: query
      name: id
      required: false
      schema:
        type: array
        items:
          type: integer
      style: form
      explode: false
      description: |
        Comma-separated list of page ids to retrieve suggestions for. If supplied, sending seed, limit, or offset parameters is an error.
    seed:
      in: query
      name: seed
      required: false
      schema:
        type: integer
      description: |
        Seed value for retreiving deterministric random results. The special value 0 (zero) gives results ordered by page id
    limit:
      in: query
      name: limit
      required: false
      schema: 
        type: integer
      description: |
        Number of pages to retrieve
    offset:
      in: query
      name: offset
      required: false
      schema:
        type: integer
      description: |
        Number of records to skip before beginning to return results
    source:
      in: query
      name: source
      required: false
      schema:
        type: string
      description: |
        Retrieve data only from the specified source. Ex: `ima` (Image Matching Algorithm) or `ms` (MediaSearch)
    nofilter:
      in: query
      name: nofilter
      required: false
      schema:
        type: string
      description: |
        Whether to filter pages with no suggestions out of the response. `false` (or omitted) to filter, `true` to not filter
    domain:
      in: path
      name: domain
      required: true
      schema:
        type: string
      description: |
        Project domain for the requested data.
    title:
      in: path
      name: title
      required: true
      schema:
        type: string
      description: |
        Page title. Use underscores instead of spaces. Example: `Main_Page`
    wiki:
      in: path
      name: wiki
      required: true
      schema:
        type: string
      description: |
        WMF wiki type. Example `wikipedia` or `wiktionary`.
    lang:
      in: path
      name: lang
      required: true
      schema:
        type: string
      description: |
        Wiki language abbrevation. Example: `en` or `es`. Languages currently supported are found in `lib/wikiId.js` in the source code.
