openapi: 3.0.0
info:
  title: Image Suggestion API
  description: Documentation for Image Suggestion REST API endpoints
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: Wikimedia Platform Engineering Team
    url: https://www.mediawiki.org/wiki/Platform_Engineering_Team
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
  x-default-params:
    domain: api.wikimedia.org

paths:
  # from routes/root.js
  /image-suggestions/v0/{lang}/{wiki}/pages:
    get:
      tags:
        - Image Suggestions
      description: Gets image suggestions for multiple under-illustrated pages
      parameters:
        - $ref: "#/components/parameters/lang"
        - $ref: "#/components/parameters/wiki"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    page:
                      type: string
                    suggestions:
                      type: array
                      items:
                        $ref: "#/components/schemas/suggestion"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
      x-amples:
        - title: Gets image suggestions for multiple under-illustrated pages
          request:
            params:
              lang: en
              wiki: wikipedia
              title: frogs
          response:
            status: 200
            headers:
              content-type: application/json
  /image-suggestions/v0/{lang}/{wiki}/pages/{title}:
    get:
      tags:
        - Page Image Suggestions
      description: Gets image suggestions for a specified page
      parameters:
        - $ref: "#/components/parameters/lang"
        - $ref: "#/components/parameters/wiki"
        - $ref: "#/components/parameters/title"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                    suggestions:
                      type: array
                      items:
                        $ref: "#/components/schemas/suggestion"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
        404:
          description: Page not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/problem"
      x-amples:
        - title: Successfully gets images for a specified page
          request:
            params:
              lang: en
              wiki: wikipedia
              title: frogs
          response:
            status: 200
            headers:
              content-type: application/json
components:
  schemas:
    problem:
      required:
        - type
      properties:
        detail:
          type: string
    suggestion:
      required:
        - type
      properties:
        filename:
          type: string
        source:
          type: string
        confidence_score:
          type: number
  parameters:
    domain:
      in: path
      name: domain
      required: true
      schema:
        type: string
      description: |
        Project domain for the requested data.
    title:
      in: path
      name: title
      required: true
      schema:
        type: string
      description: |
        Page title. Use underscores instead of spaces. Example: `Main_Page`
    lang:
      in: path
      name: lang
      required: true
      schema:
        type: string
      description: |
        Wiki language abbrevation. Example: `en` or `es`.
    wiki:
      in: path
      name: wiki
      required: true
      schema:
        type: string
      description: |
        WMF wiki type. Example `wikipedia` or `wiktionary`.
