pipelines:
  test:
    blubberfile: blubber.yaml
    stages: # run API tests
      - name: test
  rehearse: 
    blubberfile: blubber.yaml
    stages:
      - name: test # run API tests 
      - name: candidate # build Docker image and publish to WMF registry
        build: production
        publish:
          image: true
      - name: rehearsal # deploy to staging cluster
        deploy:
          test: false
          chart:
            name: 'image-suggestion-api'
          image: '${candidate.imageName}'
          tag: '${candidate.imageTag}'
  publish:
    blubberfile: blubber.yaml
    stages:
      # build Docker image, publish to WMF registry, then create a Gerrit patch
      # to upgrade image version in helm chart
      - name: production 
        build: production
        publish:
          image: true
        promote:
          - chart: image-suggestion-api
