pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: test
  production:
    blubberfile: blubber.yaml
    stages:
      - name: production
        build: production
        publish:
          image: true
        promote:
          - chart: image-suggestion-api
